[build]
entrypoints = ["src/index.ts", "src/cli.ts"]
outdir = "dist"
target = "node"
minify = true
sourcemap = "external"

[test]
coverage = true
preload = "./tests/setup.ts"

[resolve]
paths = {
  "@" = "src"
}
