codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 90%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "scripts/**/*"
  - "site/**/*"
  - "examples/**/*"
  - "dist/**/*"
