apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-logger
  template:
    metadata:
      labels:
        app: json-logger
    spec:
      containers:
        - name: json-logger
          image: json-logger:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: json-logger
spec:
  selector:
    app: json-logger
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
