import { ColorDefinition } from './types';

export const COLORS: Record<string, ColorDefinition> = {
  // Standard colors
  black: { ansi: '\x1b[30m', hex: '#000000', className: 'logsdx__color--black' },
  red: { ansi: '\x1b[31m', hex: '#ff0000', className: 'logsdx__color--red' },
  green: { ansi: '\x1b[32m', hex: '#00ff00', className: 'logsdx__color--green' },
  yellow: { ansi: '\x1b[33m', hex: '#ffff00', className: 'logsdx__color--yellow' },
  blue: { ansi: '\x1b[34m', hex: '#0000ff', className: 'logsdx__color--blue' },
  magenta: { ansi: '\x1b[35m', hex: '#ff00ff', className: 'logsdx__color--magenta' },
  cyan: { ansi: '\x1b[36m', hex: '#00ffff', className: 'logsdx__color--cyan' },
  white: { ansi: '\x1b[37m', hex: '#ffffff', className: 'logsdx__color--white' },
  
  // Bright/bold colors
  gray: { ansi: '\x1b[90m', hex: '#808080', className: 'logsdx__color--gray' },
  grey: { ansi: '\x1b[90m', hex: '#808080', className: 'logsdx__color--grey' },
  brightRed: { ansi: '\x1b[91m', hex: '#ff5555', className: 'logsdx__color--brightRed' },
  brightGreen: { ansi: '\x1b[92m', hex: '#55ff55', className: 'logsdx__color--brightGreen' },
  brightYellow: { ansi: '\x1b[93m', hex: '#ffff55', className: 'logsdx__color--brightYellow' },
  brightBlue: { ansi: '\x1b[94m', hex: '#5555ff', className: 'logsdx__color--brightBlue' },
  brightMagenta: { ansi: '\x1b[95m', hex: '#ff55ff', className: 'logsdx__color--brightMagenta' },
  brightCyan: { ansi: '\x1b[96m', hex: '#55ffff', className: 'logsdx__color--brightCyan' },
  brightWhite: { ansi: '\x1b[97m', hex: '#ffffff', className: 'logsdx__color--brightWhite' },
  
  // Common color aliases
  darkGray: { ansi: '\x1b[90m', hex: '#808080', className: 'logsdx__color--darkGray' },
  darkGrey: { ansi: '\x1b[90m', hex: '#808080', className: 'logsdx__color--darkGrey' },
  lightRed: { ansi: '\x1b[91m', hex: '#ff5555', className: 'logsdx__color--lightRed' },
  lightGreen: { ansi: '\x1b[92m', hex: '#55ff55', className: 'logsdx__color--lightGreen' },
  lightYellow: { ansi: '\x1b[93m', hex: '#ffff55', className: 'logsdx__color--lightYellow' },
  lightBlue: { ansi: '\x1b[94m', hex: '#5555ff', className: 'logsdx__color--lightBlue' },
  lightMagenta: { ansi: '\x1b[95m', hex: '#ff55ff', className: 'logsdx__color--lightMagenta' },
  lightCyan: { ansi: '\x1b[96m', hex: '#55ffff', className: 'logsdx__color--lightCyan' },
  lightWhite: { ansi: '\x1b[97m', hex: '#ffffff', className: 'logsdx__color--lightWhite' },
  
  // Additional named colors (using 256-color mode)
  orange: { ansi: '\x1b[38;5;208m', hex: '#ff8700', className: 'logsdx__color--orange' },
  pink: { ansi: '\x1b[38;5;213m', hex: '#ff87ff', className: 'logsdx__color--pink' },
  purple: { ansi: '\x1b[38;5;129m', hex: '#af00ff', className: 'logsdx__color--purple' },
  lime: { ansi: '\x1b[38;5;118m', hex: '#87ff00', className: 'logsdx__color--lime' },
  teal: { ansi: '\x1b[38;5;30m', hex: '#008787', className: 'logsdx__color--teal' },
  lavender: { ansi: '\x1b[38;5;183m', hex: '#d7afff', className: 'logsdx__color--lavender' },
  brown: { ansi: '\x1b[38;5;130m', hex: '#af5f00', className: 'logsdx__color--brown' },
  maroon: { ansi: '\x1b[38;5;88m', hex: '#870000', className: 'logsdx__color--maroon' },
  navy: { ansi: '\x1b[38;5;17m', hex: '#00005f', className: 'logsdx__color--navy' },
  olive: { ansi: '\x1b[38;5;100m', hex: '#878700', className: 'logsdx__color--olive' },
  coral: { ansi: '\x1b[38;5;209m', hex: '#ff875f', className: 'logsdx__color--coral' },
  salmon: { ansi: '\x1b[38;5;210m', hex: '#ff8787', className: 'logsdx__color--salmon' },
  gold: { ansi: '\x1b[38;5;220m', hex: '#ffd700', className: 'logsdx__color--gold' },
  silver: { ansi: '\x1b[38;5;7m', hex: '#c0c0c0', className: 'logsdx__color--silver' },
  indigo: { ansi: '\x1b[38;5;54m', hex: '#5f0087', className: 'logsdx__color--indigo' },
  violet: { ansi: '\x1b[38;5;177m', hex: '#d787ff', className: 'logsdx__color--violet' },
  turquoise: { ansi: '\x1b[38;5;80m', hex: '#5fd7d7', className: 'logsdx__color--turquoise' },
  tan: { ansi: '\x1b[38;5;180m', hex: '#d7af87', className: 'logsdx__color--tan' },
  skyBlue: { ansi: '\x1b[38;5;117m', hex: '#87d7ff', className: 'logsdx__color--skyBlue' },
  steelBlue: { ansi: '\x1b[38;5;67m', hex: '#5f87af', className: 'logsdx__color--steelBlue' },
  forestGreen: { ansi: '\x1b[38;5;28m', hex: '#008700', className: 'logsdx__color--forestGreen' },
  seaGreen: { ansi: '\x1b[38;5;29m', hex: '#00875f', className: 'logsdx__color--seaGreen' },
  crimson: { ansi: '\x1b[38;5;160m', hex: '#d70000', className: 'logsdx__color--crimson' },
  darkRed: { ansi: '\x1b[38;5;88m', hex: '#870000', className: 'logsdx__color--darkRed' },
  darkGreen: { ansi: '\x1b[38;5;22m', hex: '#005f00', className: 'logsdx__color--darkGreen' },
  darkBlue: { ansi: '\x1b[38;5;18m', hex: '#000087', className: 'logsdx__color--darkBlue' },
  darkCyan: { ansi: '\x1b[38;5;23m', hex: '#005f5f', className: 'logsdx__color--darkCyan' },
  darkMagenta: { ansi: '\x1b[38;5;90m', hex: '#870087', className: 'logsdx__color--darkMagenta' },
  darkYellow: { ansi: '\x1b[38;5;142m', hex: '#afaf00', className: 'logsdx__color--darkYellow' },
  
  // More named colors
  firebrick: { ansi: '\x1b[38;5;124m', hex: '#b22222', className: 'logsdx__color--firebrick' },
  tomato: { ansi: '\x1b[38;5;203m', hex: '#ff6347', className: 'logsdx__color--tomato' },
  chocolate: { ansi: '\x1b[38;5;166m', hex: '#d2691e', className: 'logsdx__color--chocolate' },
  goldenrod: { ansi: '\x1b[38;5;178m', hex: '#daa520', className: 'logsdx__color--goldenrod' },
  khaki: { ansi: '\x1b[38;5;222m', hex: '#f0e68c', className: 'logsdx__color--khaki' },
  limeGreen: { ansi: '\x1b[38;5;77m', hex: '#32cd32', className: 'logsdx__color--limeGreen' },
  oliveDrab: { ansi: '\x1b[38;5;64m', hex: '#6b8e23', className: 'logsdx__color--oliveDrab' },
  aquamarine: { ansi: '\x1b[38;5;122m', hex: '#7fffd4', className: 'logsdx__color--aquamarine' },
  slateBlue: { ansi: '\x1b[38;5;62m', hex: '#6a5acd', className: 'logsdx__color--slateBlue' },
  plum: { ansi: '\x1b[38;5;182m', hex: '#dda0dd', className: 'logsdx__color--plum' },
  orchid: { ansi: '\x1b[38;5;170m', hex: '#da70d6', className: 'logsdx__color--orchid' },
  peru: { ansi: '\x1b[38;5;173m', hex: '#cd853f', className: 'logsdx__color--peru' },
  sienna: { ansi: '\x1b[38;5;130m', hex: '#a0522d', className: 'logsdx__color--sienna' },
  royalBlue: { ansi: '\x1b[38;5;62m', hex: '#4169e1', className: 'logsdx__color--royalBlue' },
  mediumPurple: { ansi: '\x1b[38;5;141m', hex: '#9370db', className: 'logsdx__color--mediumPurple' },
  
  // Additional web colors
  aliceBlue: { ansi: '\x1b[38;5;231m', hex: '#f0f8ff', className: 'logsdx__color--aliceBlue' },
  antiqueWhite: { ansi: '\x1b[38;5;230m', hex: '#faebd7', className: 'logsdx__color--antiqueWhite' },
  aqua: { ansi: '\x1b[38;5;51m', hex: '#00ffff', className: 'logsdx__color--aqua' },
  azure: { ansi: '\x1b[38;5;231m', hex: '#f0ffff', className: 'logsdx__color--azure' },
  beige: { ansi: '\x1b[38;5;230m', hex: '#f5f5dc', className: 'logsdx__color--beige' },
  bisque: { ansi: '\x1b[38;5;224m', hex: '#ffe4c4', className: 'logsdx__color--bisque' },
  blanchedAlmond: { ansi: '\x1b[38;5;224m', hex: '#ffebcd', className: 'logsdx__color--blanchedAlmond' },
  burlyWood: { ansi: '\x1b[38;5;180m', hex: '#deb887', className: 'logsdx__color--burlyWood' },
  cadetBlue: { ansi: '\x1b[38;5;73m', hex: '#5f9ea0', className: 'logsdx__color--cadetBlue' },
  chartreuse: { ansi: '\x1b[38;5;118m', hex: '#7fff00', className: 'logsdx__color--chartreuse' },
  cornflowerBlue: { ansi: '\x1b[38;5;69m', hex: '#6495ed', className: 'logsdx__color--cornflowerBlue' },
  cornsilk: { ansi: '\x1b[38;5;230m', hex: '#fff8dc', className: 'logsdx__color--cornsilk' },
  darkOliveGreen: { ansi: '\x1b[38;5;64m', hex: '#556b2f', className: 'logsdx__color--darkOliveGreen' },
  darkOrange: { ansi: '\x1b[38;5;208m', hex: '#ff8c00', className: 'logsdx__color--darkOrange' },
  darkOrchid: { ansi: '\x1b[38;5;134m', hex: '#9932cc', className: 'logsdx__color--darkOrchid' },
  darkSeaGreen: { ansi: '\x1b[38;5;108m', hex: '#8fbc8f', className: 'logsdx__color--darkSeaGreen' },
  darkSlateBlue: { ansi: '\x1b[38;5;60m', hex: '#483d8b', className: 'logsdx__color--darkSlateBlue' },
  darkSlateGray: { ansi: '\x1b[38;5;59m', hex: '#2f4f4f', className: 'logsdx__color--darkSlateGray' },
  darkTurquoise: { ansi: '\x1b[38;5;44m', hex: '#00ced1', className: 'logsdx__color--darkTurquoise' },
  darkViolet: { ansi: '\x1b[38;5;92m', hex: '#9400d3', className: 'logsdx__color--darkViolet' },
  deepPink: { ansi: '\x1b[38;5;198m', hex: '#ff1493', className: 'logsdx__color--deepPink' }, 
  deepSkyBlue: { ansi: '\x1b[38;5;39m', hex: '#00bfff', className: 'logsdx__color--deepSkyBlue' },
  dimGray: { ansi: '\x1b[38;5;102m', hex: '#696969', className: 'logsdx__color--dimGray' },
  dodgerBlue: { ansi: '\x1b[38;5;33m', hex: '#1e90ff', className: 'logsdx__color--dodgerBlue' },
  floralWhite: { ansi: '\x1b[38;5;231m', hex: '#fffaf0', className: 'logsdx__color--floralWhite' },
  gainsboro: { ansi: '\x1b[38;5;252m', hex: '#dcdcdc', className: 'logsdx__color--gainsboro' },
  ghostWhite: { ansi: '\x1b[38;5;231m', hex: '#f8f8ff', className: 'logsdx__color--ghostWhite' },
  greenYellow: { ansi: '\x1b[38;5;154m', hex: '#adff2f', className: 'logsdx__color--greenYellow' },
  honeydew: { ansi: '\x1b[38;5;231m', hex: '#f0fff0', className: 'logsdx__color--honeydew' },
  hotPink: { ansi: '\x1b[38;5;205m', hex: '#ff69b4', className: 'logsdx__color--hotPink' },
  indianRed: { ansi: '\x1b[38;5;167m', hex: '#cd5c5c', className: 'logsdx__color--indianRed' },
  ivory: { ansi: '\x1b[38;5;231m', hex: '#fffff0', className: 'logsdx__color--ivory' },
  lawnGreen: { ansi: '\x1b[38;5;118m', hex: '#7cfc00', className: 'logsdx__color--lawnGreen' },
  lemonChiffon: { ansi: '\x1b[38;5;230m', hex: '#fffacd', className: 'logsdx__color--lemonChiffon' },
  lightCoral: { ansi: '\x1b[38;5;210m', hex: '#f08080', className: 'logsdx__color--lightCoral' },
  lightGoldenrodYellow: { ansi: '\x1b[38;5;230m', hex: '#fafad2', className: 'logsdx__color--lightGoldenrodYellow' },
  lightPink: { ansi: '\x1b[38;5;217m', hex: '#ffb6c1', className: 'logsdx__color--lightPink' },
  lightSalmon: { ansi: '\x1b[38;5;216m', hex: '#ffa07a', className: 'logsdx__color--lightSalmon' },
  lightSeaGreen: { ansi: '\x1b[38;5;37m', hex: '#20b2aa', className: 'logsdx__color--lightSeaGreen' },
  lightSkyBlue: { ansi: '\x1b[38;5;117m', hex: '#87cefa', className: 'logsdx__color--lightSkyBlue' },
  lightSlateGray: { ansi: '\x1b[38;5;103m', hex: '#778899', className: 'logsdx__color--lightSlateGray' },
  lightSteelBlue: { ansi: '\x1b[38;5;152m', hex: '#b0c4de', className: 'logsdx__color--lightSteelBlue' },
  linen: { ansi: '\x1b[38;5;254m', hex: '#faf0e6', className: 'logsdx__color--linen' },
  mediumAquamarine: { ansi: '\x1b[38;5;79m', hex: '#66cdaa', className: 'logsdx__color--mediumAquamarine' },
  mediumBlue: { ansi: '\x1b[38;5;20m', hex: '#0000cd', className: 'logsdx__color--mediumBlue' },
  mediumOrchid: { ansi: '\x1b[38;5;134m', hex: '#ba55d3', className: 'logsdx__color--mediumOrchid' },
  mediumSeaGreen: { ansi: '\x1b[38;5;72m', hex: '#3cb371', className: 'logsdx__color--mediumSeaGreen' },
  mediumSlateBlue: { ansi: '\x1b[38;5;99m', hex: '#7b68ee', className: 'logsdx__color--mediumSlateBlue' },
  mediumSpringGreen: { ansi: '\x1b[38;5;49m', hex: '#00fa9a', className: 'logsdx__color--mediumSpringGreen' },
  mediumTurquoise: { ansi: '\x1b[38;5;80m', hex: '#48d1cc', className: 'logsdx__color--mediumTurquoise' },
  mediumVioletRed: { ansi: '\x1b[38;5;162m', hex: '#c71585', className: 'logsdx__color--mediumVioletRed' },
  midnightBlue: { ansi: '\x1b[38;5;17m', hex: '#191970', className: 'logsdx__color--midnightBlue' },
  mintCream: { ansi: '\x1b[38;5;231m', hex: '#f5fffa', className: 'logsdx__color--mintCream' },
  mistyRose: { ansi: '\x1b[38;5;224m', hex: '#ffe4e1', className: 'logsdx__color--mistyRose' }, 
  moccasin: { ansi: '\x1b[38;5;223m', hex: '#ffe4b5', className: 'logsdx__color--moccasin' },
  navajoWhite: { ansi: '\x1b[38;5;223m', hex: '#ffdead', className: 'logsdx__color--navajoWhite' },
  oldLace: { ansi: '\x1b[38;5;230m', hex: '#fdf5e6', className: 'logsdx__color--oldLace' },
  orangeRed: { ansi: '\x1b[38;5;202m', hex: '#ff4500', className: 'logsdx__color--orangeRed' },
  paleGoldenrod: { ansi: '\x1b[38;5;223m', hex: '#eee8aa', className: 'logsdx__color--paleGoldenrod' },  
  paleGreen: { ansi: '\x1b[38;5;120m', hex: '#98fb98', className: 'logsdx__color--paleGreen' },
  paleTurquoise: { ansi: '\x1b[38;5;159m', hex: '#afeeee', className: 'logsdx__color--paleTurquoise' },
  paleVioletRed: { ansi: '\x1b[38;5;168m', hex: '#db7093', className: 'logsdx__color--paleVioletRed' },
  papayaWhip: { ansi: '\x1b[38;5;224m', hex: '#ffefd5', className: 'logsdx__color--papayaWhip' }, 
  peachPuff: { ansi: '\x1b[38;5;223m', hex: '#ffdab9', className: 'logsdx__color--peachPuff' },
  powderBlue: { ansi: '\x1b[38;5;152m', hex: '#b0e0e6', className: 'logsdx__color--powderBlue' },
  rosyBrown: { ansi: '\x1b[38;5;138m', hex: '#bc8f8f', className: 'logsdx__color--rosyBrown' },
  saddleBrown: { ansi: '\x1b[38;5;94m', hex: '#8b4513', className: 'logsdx__color--saddleBrown' },
  sandyBrown: { ansi: '\x1b[38;5;173m', hex: '#f4a460', className: 'logsdx__color--sandyBrown' },
  seashell: { ansi: '\x1b[38;5;231m', hex: '#fff5ee', className: 'logsdx__color--seashell' },
  slateGray: { ansi: '\x1b[38;5;102m', hex: '#708090', className: 'logsdx__color--slateGray' },
  snow: { ansi: '\x1b[38;5;231m', hex: '#fffafa', className: 'logsdx__color--snow' }, 
  springGreen: { ansi: '\x1b[38;5;48m', hex: '#00ff7f', className: 'logsdx__color--springGreen' },
  thistle: { ansi: '\x1b[38;5;182m', hex: '#d8bfd8', className: 'logsdx__color--thistle' },  
  wheat: { ansi: '\x1b[38;5;223m', hex: '#f5deb3', className: 'logsdx__color--wheat' },
  whiteSmoke: { ansi: '\x1b[38;5;231m', hex: '#f5f5f5', className: 'logsdx__color--whiteSmoke' }, 
  yellowGreen: { ansi: '\x1b[38;5;113m', hex: '#9acd32', className: 'logsdx__color--yellowGreen' },
};

export const TEXT_COLORS = COLORS;
export const BACKGROUND_COLORS: Record<string, ColorDefinition> = COLORS;

export const STYLE_CODES = {
  reset: { ansi: '\x1b[0m', css: 'all: unset;', className: 'logsdx__code--reset' },
  bold: { ansi: '\x1b[1m', css: 'font-weight: bold;', className: 'logsdx__code--bold' },
  dim: { ansi: '\x1b[2m', css: 'opacity: 0.7;', className: 'logsdx__code--dim' },
  italic: { ansi: '\x1b[3m', css: 'font-style: italic;', className: 'logsdx__code--italic' },
  underline: { ansi: '\x1b[4m', css: 'text-decoration: underline;', className: 'logsdx__code--underline' },
  blink: { ansi: '\x1b[5m', css: 'animation: blink 1s step-end infinite;', className: 'logsdx__code--blink' },
  inverse: { ansi: '\x1b[7m', css: 'filter: invert(100%);', className: 'logsdx__code--inverse' },
  hidden: { ansi: '\x1b[8m', css: 'visibility: hidden;', className: 'logsdx__code--hidden' },
  strikethrough: { ansi: '\x1b[9m', css: 'text-decoration: line-through;', className: 'logsdx__code--strikethrough' },
  resetBold: { ansi: '\x1b[22m', css: 'font-weight: normal;', className: 'logsdx__code--resetBold' },
  resetDim: { ansi: '\x1b[22m', css: 'opacity: 1;', className: 'logsdx__code--resetDim' },
  resetItalic: { ansi: '\x1b[23m', css: 'font-style: normal;', className: 'logsdx__code--resetItalic' },
  resetUnderline: { ansi: '\x1b[24m', css: 'text-decoration: none;', className: 'logsdx__code--resetUnderline' },
  resetBlink: { ansi: '\x1b[25m', css: 'animation: none;', className: 'logsdx__code--resetBlink' },
  resetInverse: { ansi: '\x1b[27m', css: 'filter: none;', className: 'logsdx__code--resetInverse' },
  resetHidden: { ansi: '\x1b[28m', css: 'visibility: visible;', className: 'logsdx__code--resetHidden' },
  resetStrikethrough: { ansi: '\x1b[29m', css: 'text-decoration: none;', className: 'logsdx__code--resetStrikethrough' },
  resetColor: { ansi: '\x1b[39m', css: 'color: inherit;', className: 'logsdx__code--resetColor' },
  resetBackground: { ansi: '\x1b[49m', css: 'background-color: transparent;', className: 'logsdx__code--resetBackground' },
};
